// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqcatlpsindjoosssqil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxY2F0bHBzaW5kam9vc3NzcWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTY2NDIsImV4cCI6MjA2MTQzMjY0Mn0.iWbA6EP4xeiEaBn2HRddEN922yKQrSmO4TzjtPlNS9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);